consumer.alias=default
bootstrap.servers=
consumer.topic=
group.id=
value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
poll.retries=5
poll.interval.ms=1000
max.poll.records=500
schema.registry.url=
ssl.enabled=false
ssl.keystore.location=
ssl.keystore.password=
ssl.key.password=
