consumer.alias=default
bootstrap.servers=
consumer.topic=
group.id=
value.deserializer=string
poll.retries=5
poll.interval.ms=1000
max.poll.records=500
schema.registry.url=
shared.secret=
ssl.enabled=false
ssl.truststore.location=
ssl.truststore.password=
ssl.truststore.type=
ssl.keystore.location=
ssl.keystore.password=
ssl.keystore.type=
ssl.key.password=
schema.registry.ssl.truststore.location=
schema.registry.ssl.truststore.password=
schema.registry.ssl.keystore.location=
schema.registry.ssl.keystore.password=
schema.registry.ssl.key.password=
