package com.ing.ide.main.mainui.components.testdesign.tree;

import com.ing.datalib.model.Tag;
import com.ing.ide.util.jslist.JSList;
import java.util.List;
import java.util.function.BiConsumer;
import java.util.function.Consumer;
import java.util.function.Function;
import javax.swing.JFrame;

/**
 *
 *
 */
public class TagEditorDialog extends javax.swing.JDialog {
    /**
     * Creates new form NewJDialog
     *
     * @param parent
     * @param model
     * @param modal
     */
    JSList<Tag> jslist;

    public TagEditorDialog(
        JFrame parent,
        boolean modal,
        List<Tag> model,
        Function<String, Tag> onAdd,
        BiConsumer<Tag, String> onUpdate
    ) {
        super(parent, modal);
        initComponents();
        jslist = new JSList(model, t -> ((Tag) t).getValue(), onAdd);
        if (onUpdate != null) {
            jslist.withOnUpdate(onUpdate);
        }
        // Fix bottom padding issue: wrap the jslist panel so clicking empty space
        // beneath the list does not interact with the last row
        javax.swing.JPanel wrapper = new javax.swing.JPanel(new java.awt.BorderLayout());
        wrapper.add(jslist, java.awt.BorderLayout.CENTER);
        // Add a filler at the bottom so the list doesn't stretch to fill empty clickable space
        javax.swing.Box.Filler filler = new javax.swing.Box.Filler(
            new java.awt.Dimension(0, 0),
            new java.awt.Dimension(0, 0),
            new java.awt.Dimension(Short.MAX_VALUE, 0)
        );
        wrapper.add(filler, java.awt.BorderLayout.PAGE_END);
        panel.add(wrapper);

        // Add a confirm/close button at the bottom
        javax.swing.JButton confirmButton = new javax.swing.JButton("Done");
        confirmButton.addActionListener(
            e -> {
                // Save and close - the onSelect callback already fires on each change,
                // so we just close the dialog.
                dispose();
            }
        );
        javax.swing.JPanel buttonPanel = new javax.swing.JPanel();
        buttonPanel.add(confirmButton);
        getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);
    }

    public void show(Consumer<List<Tag>> onsel) {
        setOnSelection(onsel);
        setVisible(true);
    }

    public static TagEditorDialog build(
        JFrame parent,
        List<Tag> model,
        List<Tag> selected,
        Consumer<Tag> onRemove,
        Function<String, Tag> onAdd,
        BiConsumer<Tag, String> onUpdate
    ) {
        TagEditorDialog dialog = new TagEditorDialog(parent, true, model, onAdd, onUpdate);
        dialog.jslist.withOnRemove(onRemove);
        dialog.jslist.setSelected(selected);
        dialog.setLocationRelativeTo(parent);
        return dialog;
    }

    private void setOnSelection(Consumer<List<Tag>> onsel) {
        jslist.setOnSelect(onsel);
    }

    public TagEditorDialog withTitle(String title) {
        setTitle(title);
        return this;
    }

    public List<Tag> getSelected() {
        return jslist.getSelected();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        panel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Tag");
        setResizable(false);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 302, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 350, Short.MAX_VALUE)
        );

        getContentPane().add(panel, java.awt.BorderLayout.CENTER);

        pack();
    } // </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
