
package com.ing.ide.main.utils.toasterNotification;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.UIManager;

/**
 *
 * 
 */
public class ToasterDialog extends javax.swing.JDialog {

    // Notification type constants
    public static final int TYPE_INFO = 0;
    public static final int TYPE_SUCCESS = 1;
    
    // Translucent colors for notifications
    private static final Color SUCCESS_BG = new Color(76, 175, 80, 220);  // Translucent green
    private static final Color INFO_BG = new Color(33, 150, 243, 220);     // Translucent blue
    private static final Color TEXT_COLOR = Color.WHITE;
    
    ToasterDialog() {
        this(TYPE_INFO);
    }
    
    ToasterDialog(int notificationType) {
        initComponents();
        applyStyle(notificationType);
    }
    
    private void applyStyle(int notificationType) {
        Color bgColor = (notificationType == TYPE_SUCCESS) ? SUCCESS_BG : INFO_BG;
        
        // Style the dialog
        getContentPane().setBackground(bgColor);
        jScrollPane1.setBackground(bgColor);
        jScrollPane1.getViewport().setBackground(bgColor);
        jScrollPane1.setBorder(BorderFactory.createEmptyBorder(8, 12, 8, 12));
        jScrollPane1.setOpaque(true);
        
        // Style the message text area
        message.setBackground(bgColor);
        message.setForeground(TEXT_COLOR);
        message.setOpaque(true);
        message.setBorder(BorderFactory.createEmptyBorder());
        
        // Add a subtle border around the dialog
        getRootPane().setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(bgColor.darker(), 1),
            BorderFactory.createEmptyBorder(4, 4, 4, 4)
        ));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        message = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAutoRequestFocus(false);
        setMinimumSize(new java.awt.Dimension(300, 80));
        setUndecorated(true);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(226, 75));

        message.setEditable(false);
        message.setColumns(20);
        message.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        message.setLineWrap(true);
        message.setRows(5);
        message.setText("Test notification");
        message.setWrapStyleWord(true);
        message.setMaximumSize(new java.awt.Dimension(224, 70));
        message.setPreferredSize(new java.awt.Dimension(224, 70));
        jScrollPane1.setViewportView(message);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea message;
    // End of variables declaration//GEN-END:variables
}
