enableTracing=false
RerunTimes=0
slacknotify=false
TakeFullPageScreenShot=true
AzureReport=false
recordVideo=false
ExecutionMode=Local
IterationMode=BreakOnError
ScreenShotFor=Both
reportPerformanceLog=false
enableHAR=false
ThreadCount=10
TestEnv=Default
ExecutionTimeOut=8
RemoteGridURL=http://localhost:4444/wd/hub
ReportPortal=false
bddReport=false
ExtentReport=true
