package com.ing.engine.perf;

import java.io.File;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.security.MessageDigest;
import java.time.LocalDate;

/**
 * Provenance header for generated k6 scripts.
 *
 * <p>Every generated script starts with a marker block containing the source,
 * the regenerate command and a fingerprint of the generated body. On
 * re-export, {@link #isHandEdited(File)} detects whether the on-disk file
 * still matches its own fingerprint — if not, the user edited it and the
 * exporter must refuse to overwrite without {@code --force}.
 */
public final class ScriptProvenance {
    private static final String MARKER = "// GENERATED BY INGENIOUS PERF STUDIO";
    private static final String FINGERPRINT_PREFIX = "// ingenious:fingerprint ";

    private ScriptProvenance() {}

    /** Prepend the provenance header (marker, source, regenerate hint, fingerprint). */
    public static String wrap(String source, String regenerate, String profileName, String body) {
        StringBuilder sb = new StringBuilder();
        sb.append(MARKER).append(" — source: ").append(source);
        sb.append(" (").append(LocalDate.now()).append(", profile: ").append(profileName);
        sb.append(")\n");
        if (regenerate != null && !regenerate.isEmpty()) {
            sb.append("// Regenerate: ").append(regenerate).append('\n');
        }
        sb.append(FINGERPRINT_PREFIX).append(sha1(body)).append('\n');
        sb.append('\n');
        sb.append(body);
        return sb.toString();
    }

    /** True when the file carries the generated-script marker. */
    public static boolean isGenerated(File file) {
        String content = readOrNull(file);
        return content != null && content.startsWith(MARKER);
    }

    /**
     * True when the file was generated but its body no longer matches the
     * embedded fingerprint (i.e. someone edited it by hand). Files without a
     * marker are treated as hand-written and also return {@code true}.
     */
    public static boolean isHandEdited(File file) {
        String content = readOrNull(file);
        if (content == null) {
            return false; // nothing on disk = nothing to protect
        }
        if (!content.startsWith(MARKER)) {
            return true;
        }
        int fpStart = content.indexOf(FINGERPRINT_PREFIX);
        if (fpStart < 0) {
            return true;
        }
        int fpLineEnd = content.indexOf('\n', fpStart);
        if (fpLineEnd < 0) {
            return true;
        }
        String recorded = content
            .substring(fpStart + FINGERPRINT_PREFIX.length(), fpLineEnd)
            .trim();
        // body = everything after the blank line following the fingerprint
        int bodyStart = fpLineEnd + 1;
        if (bodyStart < content.length() && content.charAt(bodyStart) == '\n') {
            bodyStart++;
        }
        String body = content.substring(bodyStart);
        return !recorded.equals(sha1(body));
    }

    /**
     * The generation source recorded in the header, e.g.
     * {@code TestPlan/APIBasics/CreatePost} or {@code rec.har};
     * null when the file is not a generated script.
     */
    public static String sourceOf(File file) {
        String header = firstLine(file);
        if (header == null || !header.startsWith(MARKER)) {
            return null;
        }
        int start = header.indexOf("source: ");
        if (start < 0) {
            return null;
        }
        start += "source: ".length();
        int end = header.lastIndexOf(" (");
        if (end <= start) {
            return null;
        }
        return header.substring(start, end).trim();
    }

    /** Script flavor from the regenerate hint: "http" or "browser" (default http). */
    public static String typeOf(File file) {
        String content = readOrNull(file);
        if (content == null) {
            return "http";
        }
        int regen = content.indexOf("// Regenerate: ");
        if (regen >= 0) {
            int lineEnd = content.indexOf('\n', regen);
            String line = lineEnd > regen ? content.substring(regen, lineEnd) : "";
            if (line.contains("--type browser")) {
                return "browser";
            }
        }
        return "http";
    }

    private static String firstLine(File file) {
        String content = readOrNull(file);
        if (content == null) {
            return null;
        }
        int nl = content.indexOf('\n');
        return nl > 0 ? content.substring(0, nl) : content;
    }

    static String sha1(String s) {
        try {
            MessageDigest md = MessageDigest.getInstance("SHA-1");
            byte[] digest = md.digest(s.getBytes(StandardCharsets.UTF_8));
            StringBuilder sb = new StringBuilder();
            for (byte b : digest) {
                sb.append(String.format("%02x", b));
            }
            return sb.toString();
        } catch (Exception e) {
            throw new IllegalStateException("SHA-1 unavailable", e);
        }
    }

    private static String readOrNull(File file) {
        try {
            return file.isFile()
                ? new String(Files.readAllBytes(file.toPath()), StandardCharsets.UTF_8)
                : null;
        } catch (Exception e) {
            return null;
        }
    }
}
