
package com.ing.ide.main.ui;

import com.ing.datalib.testdata.TestDataFactory;
import com.ing.ide.main.mainui.AppMainFrame;
import com.ing.ide.main.utils.Utils;
import com.ing.ide.util.Validator;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;

public class NewProject extends javax.swing.JDialog {

    private final AppMainFrame sMainFrame;

    private Boolean created = false;

    public NewProject(AppMainFrame sMainFrame) throws IOException {
        this.sMainFrame = sMainFrame;
        initComponents();

        setIconImage(((ImageIcon) Utils.getIconByResourceName("/ui/resources/main/NewProject")).getImage());
        String currDirectory = new File(System.getProperty("user.dir")).getCanonicalPath() + File.separator + "Projects";
        fileChooser.setCurrentDirectory(new File(currDirectory));
        projLocation.setText(fileChooser.getCurrentDirectory().getAbsolutePath());
    }

    public void createNew() {
        created = false;
        setSize(480, 270);
        error.setText("  ");
        setLocationRelativeTo(null);
        testDataType.setModel(new DefaultComboBoxModel(TestDataFactory.getDATA_PROVIDER_NAMES().toArray()));
        setVisible(true);
    }

    public Boolean isCreated() {
        return created;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        testDataType = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        error = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        projName = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        projLocation = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        createProject = new javax.swing.JButton();

        fileChooser.setDialogTitle("Select Project Location");
        fileChooser.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        testDataType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Testdata Type");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create New Project");
        setMinimumSize(new java.awt.Dimension(120, 300));
        setModal(true);
        setPreferredSize(new java.awt.Dimension(602, 320));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        jPanel3.setMinimumSize(new java.awt.Dimension(120, 100));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 5, 0));
        jPanel1.setLayout(new java.awt.GridLayout(1, 1));

        error.setForeground(java.awt.Color.red);
        error.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        error.setText(" ");
        jPanel1.add(error);

        jPanel3.add(jPanel1);

        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 5, 0));
        jPanel5.setLayout(new java.awt.GridLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Project Name");
        jLabel3.setAlignmentX(-0.05F);
        jPanel5.add(jLabel3);

        jPanel3.add(jPanel5);

        jPanel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 5, 0));
        jPanel6.setLayout(new java.awt.GridLayout());

        projName.setText("NewProject");
        projName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projNameActionPerformed(evt);
            }
        });
        jPanel6.add(projName);

        jPanel3.add(jPanel6);

        getContentPane().add(jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.Y_AXIS));

        jPanel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 5, 0));
        jPanel7.setLayout(new java.awt.GridLayout());

        jLabel4.setText("Project Location");
        jPanel7.add(jLabel4);

        jPanel4.add(jPanel7);

        jPanel8.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 5, 0));
        jPanel8.setLayout(new java.awt.GridLayout());

        projLocation.setEditable(false);
        projLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projLocationActionPerformed(evt);
            }
        });
        jPanel8.add(projLocation);

        jPanel4.add(jPanel8);

        getContentPane().add(jPanel4);

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 0, 20, 0));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        createProject.setText("Create Project");
        createProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createProjectActionPerformed(evt);
            }
        });
        jPanel2.add(createProject, new java.awt.GridBagConstraints());

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createProjectActionPerformed
        createProject();
    }//GEN-LAST:event_createProjectActionPerformed

    private void projNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projNameActionPerformed
        createProject.doClick();
    }//GEN-LAST:event_projNameActionPerformed

    private void projLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projLocationActionPerformed
        projLocation.setText(System.getProperty("user.dir") + File.separator + "Projects");
    }//GEN-LAST:event_projLocationActionPerformed

    private void createProject() {
        if (Validator.isValidName(projName.getText().trim())) {
            String location = System.getProperty("user.dir") + File.separator + "Projects";
           /* if (projLocation.getText().trim().isEmpty()) {
                location = System.getProperty("user.dir") + File.separator + "Projects";
            } else {
                location = FilenameUtils.getFullPath(projLocation.getText().trim());
            }*/
            createProject(location);
        } else {
            error.setText("Invalid Project Name");
        }
    }

    private void createProject(String location) {
        File file = null;
        try {
            String fileloc = new File(location + File.separator + projName.getText()).getCanonicalPath();
            file = new File(fileloc);
        } catch (IOException ex) {
            Logger.getLogger(NewProject.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (!file.exists()
                && (sMainFrame.getProject() == null
                || !sMainFrame.getProject().getLocation().equals(file.getAbsolutePath()))) {
            sMainFrame.createProject(projName.getText().trim(), location, testDataType.getSelectedItem().toString());
            created = true;
            dispose();
        } else {
            error.setText("Project Location is not Empty / Project already present in the location");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createProject;
    private javax.swing.JLabel error;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField projLocation;
    private javax.swing.JTextField projName;
    private javax.swing.JComboBox<String> testDataType;
    // End of variables declaration//GEN-END:variables
}
