package com.ing.engine.perf;

import static org.assertj.core.api.Assertions.assertThat;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import java.util.ArrayList;
import java.util.List;
import org.testng.annotations.Test;

/**
 * Phase 2 conformance: k6 browser script emission and browser-appropriate
 * options (scenarios + Web Vitals thresholds).
 */
public class K6BrowserScriptTest {

    @Test
    public void browserOptionsWrapProfileInUiScenario() {
        ObjectMapper mapper = new ObjectMapper();
        ObjectNode smoke = K6BrowserScriptGenerator.browserOptions(
            mapper,
            PerfProfile.builtIn("smoke")
        );
        assertThat(smoke.at("/scenarios/ui/executor").asText()).isEqualTo("constant-vus");
        assertThat(smoke.at("/scenarios/ui/vus").asInt()).isEqualTo(1);
        assertThat(smoke.at("/scenarios/ui/options/browser/type").asText()).isEqualTo("chromium");
        // http_req_* thresholds are replaced by browser-appropriate ones
        assertThat(smoke.at("/thresholds/http_req_duration").isMissingNode()).isTrue();
        assertThat(smoke.at("/thresholds/checks/0").asText()).isEqualTo("rate==1.0");
        assertThat(smoke.at("/thresholds/browser_web_vital_lcp/0").asText())
            .isEqualTo("p(95)<2500");

        ObjectNode average = K6BrowserScriptGenerator.browserOptions(
            mapper,
            PerfProfile.builtIn("average")
        );
        assertThat(average.at("/scenarios/ui/executor").asText()).isEqualTo("ramping-vus");
        assertThat(average.at("/scenarios/ui/stages")).hasSize(3);
    }

    @Test
    public void generatedBrowserScriptHasExpectedShape() {
        List<String> lines = new ArrayList<>();
        lines.add("await page.goto('http://localhost:3000/signin', { waitUntil: 'load' });");
        lines.add("await page.locator('#username').fill('john');");
        lines.add(
            "check(await page.getByRole('button', { name: 'Sign in' }).isVisible(), " +
            "{ 'signin visible': (v) => v });"
        );
        List<String> warnings = new ArrayList<>();
        warnings.add("something dynamic");
        String script = K6BrowserScriptGenerator.generate(
            "TestPlan/Registration/Registration",
            "ingenious perf export \"P/Registration/Registration\" --type browser --profile smoke",
            PerfProfile.builtIn("smoke"),
            lines,
            warnings
        );
        assertThat(script).startsWith("// GENERATED BY INGENIOUS PERF STUDIO");
        assertThat(script).contains("import { browser } from 'k6/browser';");
        assertThat(script).contains("import { check } from 'k6';");
        assertThat(script).contains("//   - something dynamic");
        assertThat(script).contains("export default async function () {");
        assertThat(script).contains("const page = await browser.newPage();");
        assertThat(script).contains("try {");
        assertThat(script)
            .contains(
                "    await page.goto('http://localhost:3000/signin', { waitUntil: 'load' });"
            );
        assertThat(script).contains("} finally {");
        assertThat(script).contains("await page.close();");
        assertThat(script).contains("\"type\" : \"chromium\"");
    }
}
