package com.ing.engine.perf;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.File;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.List;
import org.testng.annotations.Test;

/**
 * Phase 1 conformance: k6 HTTP script emission, JS escaping, HAR ingestion
 * filters and provenance-based overwrite protection.
 */
public class K6ScriptGenerationTest {

    // ------------------------------------------------------------------
    // JS emission
    // ------------------------------------------------------------------

    @Test
    public void jsEscapingIsInjectionSafe() {
        assertThat(K6HttpScriptGenerator.js("plain")).isEqualTo("'plain'");
        assertThat(K6HttpScriptGenerator.js("it's")).isEqualTo("'it\\'s'");
        assertThat(K6HttpScriptGenerator.js("a\\b")).isEqualTo("'a\\\\b'");
        assertThat(K6HttpScriptGenerator.js("line1\nline2")).isEqualTo("'line1\\nline2'");
        assertThat(K6HttpScriptGenerator.js("'); evil(('")).isEqualTo("'\\'); evil((\\''");
        assertThat(K6HttpScriptGenerator.js(null)).isEqualTo("''");
    }

    @Test
    public void generatedScriptHasExpectedShape() {
        HttpRequestSpec get = new HttpRequestSpec();
        get.method = "get";
        get.url = "https://api.example.com/users/1";
        get.name = "GET /users/1";
        get.checkStatus = 200;

        HttpRequestSpec post = new HttpRequestSpec();
        post.method = "post";
        post.url = "https://api.example.com/users";
        post.name = "POST /users";
        post.body = "{\"name\":\"Ada\"}";
        post.headers.add(new String[] { "Content-Type", "application/json" });
        post.checkStatus = 201;

        List<HttpRequestSpec> requests = new ArrayList<>();
        requests.add(get);
        requests.add(post);
        String script = K6HttpScriptGenerator.generate(
            "TestPlan/API/TC",
            "ingenious perf export \"P/API/TC\" --type http --profile smoke",
            PerfProfile.builtIn("smoke"),
            requests,
            new ArrayList<String>()
        );

        assertThat(script).startsWith("// GENERATED BY INGENIOUS PERF STUDIO");
        assertThat(script).contains("// Regenerate: ingenious perf export");
        assertThat(script).contains("import http from 'k6/http';");
        assertThat(script).contains("import { check, group, sleep } from 'k6';");
        assertThat(script).contains("export const options = ");
        assertThat(script).contains("\"vus\" : 1");
        assertThat(script).contains("group('GET /users/1', function () {");
        assertThat(script).contains("const res = http.get('https://api.example.com/users/1');");
        assertThat(script).contains("'status is 200': (r) => r.status === 200");
        // POST: body + params ordering
        assertThat(script)
            .contains("http.post('https://api.example.com/users', '{\"name\":\"Ada\"}', params);");
        assertThat(script).contains("'Content-Type': 'application/json',");
        assertThat(script).contains("export default function () {");
        assertThat(script).contains("sleep(1);");
    }

    @Test
    public void deleteMapsToDelAndWarningsAreEmbedded() {
        HttpRequestSpec del = new HttpRequestSpec();
        del.method = "delete";
        del.url = "https://api.example.com/users/1";
        del.name = "DELETE /users/1";
        del.comments.add("TODO: something");
        List<HttpRequestSpec> requests = new ArrayList<>();
        requests.add(del);
        List<String> warnings = new ArrayList<>();
        warnings.add("a warning");
        String script = K6HttpScriptGenerator.generate(
            "x",
            null,
            PerfProfile.builtIn("smoke"),
            requests,
            warnings
        );
        assertThat(script).contains("http.del('https://api.example.com/users/1', null);");
        assertThat(script).contains("//   - a warning");
        assertThat(script).contains("// TODO: something");
    }

    // ------------------------------------------------------------------
    // provenance
    // ------------------------------------------------------------------

    @Test
    public void provenanceDetectsHandEdits() throws Exception {
        File dir = Files.createTempDirectory("prov-test").toFile();
        try {
            File f = new File(dir, "s.js");
            String script = ScriptProvenance.wrap("src", "regen", "smoke", "body();\n");
            Files.write(f.toPath(), script.getBytes(StandardCharsets.UTF_8));
            assertThat(ScriptProvenance.isGenerated(f)).isTrue();
            assertThat(ScriptProvenance.isHandEdited(f)).isFalse();
            // simulate a hand edit
            Files.write(
                f.toPath(),
                script.replace("body();", "body(); hacked();").getBytes(StandardCharsets.UTF_8)
            );
            assertThat(ScriptProvenance.isHandEdited(f)).isTrue();
            // hand-written file without marker
            File plain = new File(dir, "plain.js");
            Files.write(plain.toPath(), "console.log(1);\n".getBytes(StandardCharsets.UTF_8));
            assertThat(ScriptProvenance.isGenerated(plain)).isFalse();
            assertThat(ScriptProvenance.isHandEdited(plain)).isTrue();
            // missing file = nothing to protect
            assertThat(ScriptProvenance.isHandEdited(new File(dir, "nope.js"))).isFalse();
        } finally {
            for (File c : dir.listFiles()) {
                c.delete();
            }
            dir.delete();
        }
    }

    // ------------------------------------------------------------------
    // HAR ingestion
    // ------------------------------------------------------------------

    private static final String HAR =
        "{ \"log\": { \"entries\": [" +
        // API call with credential + noise headers
        "{ \"request\": { \"method\": \"POST\", \"url\": \"https://api.example.com/login\"," +
        "  \"headers\": [" +
        "    {\"name\": \"Content-Type\", \"value\": \"application/json\"}," +
        "    {\"name\": \"Authorization\", \"value\": \"Bearer secret\"}," +
        "    {\"name\": \"Cookie\", \"value\": \"sid=1\"}," +
        "    {\"name\": \"Content-Length\", \"value\": \"42\"}," +
        "    {\"name\": \":authority\", \"value\": \"api.example.com\"}" +
        "  ]," +
        "  \"postData\": {\"text\": \"{\\\"u\\\":\\\"a\\\"}\"} }," +
        "  \"response\": {\"status\": 200, \"content\": {\"mimeType\": \"application/json\"}} }," +
        // static asset -> filtered
        "{ \"request\": { \"method\": \"GET\", \"url\": \"https://cdn.example.com/app.css\", \"headers\": [] }," +
        "  \"response\": {\"status\": 200, \"content\": {\"mimeType\": \"text/css\"}} }," +
        // preflight -> filtered
        "{ \"request\": { \"method\": \"OPTIONS\", \"url\": \"https://api.example.com/login\", \"headers\": [] }," +
        "  \"response\": {\"status\": 204, \"content\": {\"mimeType\": \"\"}} }," +
        // plain GET
        "{ \"request\": { \"method\": \"GET\", \"url\": \"https://api.example.com/me\", \"headers\": [] }," +
        "  \"response\": {\"status\": 401, \"content\": {\"mimeType\": \"application/json\"}} }" +
        "] } }";

    @Test
    public void harReaderFiltersAndScrubs() throws Exception {
        File dir = Files.createTempDirectory("har-test").toFile();
        try {
            File har = new File(dir, "rec.har");
            Files.write(har.toPath(), HAR.getBytes(StandardCharsets.UTF_8));
            HarReader.Result result = HarReader.read(har, null, false);
            assertThat(result.requests).hasSize(2);
            HttpRequestSpec login = result.requests.get(0);
            assertThat(login.method).isEqualTo("post");
            assertThat(login.body).isEqualTo("{\"u\":\"a\"}");
            assertThat(login.checkStatus).isEqualTo(200);
            // only Content-Type survives the scrub/drop rules
            assertThat(login.headers).hasSize(1);
            assertThat(login.headers.get(0)[0]).isEqualTo("Content-Type");
            assertThat(login.comments.toString()).contains("Authorization");
            assertThat(result.warnings.toString()).contains("scrubbed");
            // second surviving request keeps its observed status
            assertThat(result.requests.get(1).checkStatus).isEqualTo(401);

            // urlFilter narrows further
            HarReader.Result filtered = HarReader.read(har, "/me", false);
            assertThat(filtered.requests).hasSize(1);
            assertThat(filtered.requests.get(0).url).endsWith("/me");

            // includeStatic keeps the css
            HarReader.Result withStatic = HarReader.read(har, null, true);
            assertThat(withStatic.requests).hasSize(3);
        } finally {
            for (File c : dir.listFiles()) {
                c.delete();
            }
            dir.delete();
        }
    }

    @Test
    public void staticAssetDetectionCoversExtensionAndMime() {
        assertThat(HarReader.isStaticAsset("https://x.com/a.png", "")).isTrue();
        assertThat(HarReader.isStaticAsset("https://x.com/a?f=1", "image/png")).isTrue();
        assertThat(HarReader.isStaticAsset("https://x.com/api/users", "application/json"))
            .isFalse();
    }
}
