db.alias=BANCSDayDB
connectionString=jdbc:sqlserver://%regionName%-BIABSQLN07.biab.au.ing.net\\DBS1:1773;database=BancsDay;encrypt=false;trustServerCertificate=false;multisubnetfailover=true
password=4UxUb4Gu
driver=com.mysql.cj.jdbc.Driver
commit=true
user=testteam
timeout=90
