db.alias=PaymentsDB
connectionString=jdbc:sqlserver://%regionName%-BIABSQLN05.biab.au.ing.net\\DBS1:1771;database=Payment;encrypt=false;trustServerCertificate=true;multisubnetfailover=true
password=4UxUb4Gu
driver=com.mysql.cj.jdbc.Driver
commit=false
user=testteam
timeout=60
