globalHttpProxy=FALSE
dedicatedProxy=FALSE
w3c=FALSE
timezone=
project=
language=
blockDomains=[]
video=TRUE
media=
locale=
deviceName=eeee
network=FALSE
lambdaMaskCommands=[]
newCommandTimeout=60
platformVersion=
automationName=
otherApps=[]
platformName=eeeee
app=
console=FALSE
orientation=auto
proxyUrl=
privateCloud=FALSE
isRealMobile=FALSE1
enableBluetooth=FALSE
devicelog=FALSE
disableAnimation=FALSE
build=Untitled
geoLocation=
autoLaunch=TRUE
enableImageInjection=FALSE
idleTimeout=120
name=
autoGrantPermissions=FALSE
deviceOrientation=PORTRAIT
waitForIdleTimeout=
eventTimings=FALSE
region=
queueTimeout=600
tunnel=FALSE
tunnelName=
