storageStatePath=
setIsMobile=
setRecordVideoSize=
setTimezoneId=
useStorageState=
setUserAgent=
isAuthenticated=true
setScreenSize=
userID=admin
setRecordVideoDir=
setGeolocation=
setOffline=
password=password
setViewportSize=
setDeviceScaleFactor=
pageTimeout=60000
setHasTouch=
setLocale=
