storageStatePath=
setIsMobile=
setRecordVideoSize=
setTimezoneId=
useStorageState=
setUserAgent=
isAuthenticated=true
setScreenSize=
userID=biabad\\lfmanagement20
setRecordVideoDir=
setGeolocation=
setOffline=
password=FV0grc1j16k9GUE
setViewportSize=
setDeviceScaleFactor=
pageTimeout=30000
setHasTouch=
setLocale=
