storageStatePath=
setIsMobile=
setRecordVideoSize=
setTimezoneId=
useStorageState=
setUserAgent=
isAuthenticated=true
setScreenSize=
userID=mrusera
setRecordVideoDir=
setGeolocation=
setOffline=
password=Labuser1
setViewportSize=
setDeviceScaleFactor=
pageTimeout=30000
setHasTouch=
setLocale=
