producer.alias=default
bootstrap.servers=
producer.topic=
key.serializer=org.apache.kafka.common.serialization.StringSerializer
value.serializer=org.apache.kafka.common.serialization.StringSerializer
partition=
schema.registry.url=
auto.register.schemas=false
shared.secret=
ssl.enabled=false
ssl.keystore.location=
ssl.keystore.password=
ssl.key.password=
