producer.alias=default
bootstrap.servers=
producer.topic=
key.serializer=string
value.serializer=string
partition=
schema.registry.url=
auto.register.schemas=false
shared.secret=
ssl.enabled=false
ssl.truststore.location=
ssl.truststore.password=
ssl.truststore.type=
ssl.keystore.location=
ssl.keystore.password=
ssl.keystore.type=
ssl.key.password=
schema.registry.ssl.truststore.location=
schema.registry.ssl.truststore.password=
schema.registry.ssl.keystore.location=
schema.registry.ssl.keystore.password=
schema.registry.ssl.key.password=
