db.alias=regdb
driver={[Shared] RegShared:DbDriver}
connectionString=jdbc:regmark:{[Project] DataScope:DbConn}-%dbEnv%-{[Shared] RegShared:SVal}
user=svc_{DataScope:PLower}
password={[Project] DataScope:PVal}
commit=false
timeout={DataScope:DbTimeout}
